networks:
    modx-pd-site-network:
        driver: bridge
        name: modx-pd-site-network

services:
    modx_nginx:
        container_name: modx_nginx
        build:
            context: ./
            dockerfile: docker/nginx/Dockerfile
        volumes:
            - ./modx:/var/www/modx
            - ./docker/nginx/conf.d:/etc/nginx/conf.d
        ports:
            - "80:80"
        expose:
            - 80
        networks:
            - modx-pd-site-network
        depends_on:
            site: { condition: service_started }

    site:
        container_name: site
        build:
            context: ./
            dockerfile: ./docker/php-fpm7.4/Dockerfile
        networks:
            - modx-pd-site-network
        volumes:
            - ./modx:/var/www/modx
            - ./.env:/var/www/modx/.env

    db_modx:
        container_name: db_modx
        image: mysql:5.6
        restart: always
        ports:
            - "3306:3306"
        environment:
            MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
            MYSQL_DATABASE: ${DB_NAME}
            MYSQL_USER: ${DB_USER}
            MYSQL_PASSWORD: ${DB_PASSWORD}
        networks:
            - modx-pd-site-network
        volumes:
            - ./docker/mysql/volume:/var/lib/mysql
        command: ['mysqld', '--character-set-server=utf8mb4', '--collation-server=utf8mb4_general_ci']

    phpmyadmin:
        depends_on:
            - db_modx
        image: phpmyadmin
        restart: always
        ports:
            - "8090:80"
        environment:
            PMA_HOST: db_modx
            PMA_USER: root
            PMA_PASSWORD: 'modx_pass'
            PMA_PORT: 3306
        networks:
            - modx-pd-site-network