networks:
    modx-pd-site-network:
        driver: bridge
        name: modx-pd-site-network

services:
    db_modx:
        container_name: db_modx
        image: mysql:5.6
        restart: always
        ports:
            - "3306:3306"
        environment:
            MYSQL_ROOT_PASSWORD: modx_pass
            MYSQL_DATABASE: modx
            MYSQL_USER: modx
            MYSQL_PASSWORD: modx_pass
        networks:
            - modx-pd-site-network
        volumes:
            - ./docker/mysql/volume:/var/lib/mysql
        command: ['mysqld', '--character-set-server=utf8mb4', '--collation-server=utf8mb4_general_ci']